language: node_js
node_js:
- '12.16'
deploy:
provider: heroku
  api_key:
    secure: LYM9hJGoshGqkIWi+f9vq0Au1Z7f3cjQEFmLIPY/RpVRWMZBEtTnm083vq8pIpmh6InOEEyFRa3bzC6+kGnPVthqVWlI0rM4ZCe97gSFJZbwvdiQVKVaeEZf9T9tvAB1Yum6w/s4m7iBgM5kK2XywTQdCmEj8KxII/eOQtaBkfEWC54Dz8D9jLKpjhwsAhg6aJxVZv+katGoNKqE8SIMnsIrYgSS2hV2ngR/f585a1iFiOs/rRvL3euxdaa+LeO2lUzcc8q82XVqs146na/iViY2/sK4t4eaZiDb2QQoupmpjTA9M/fsW6cb02b/roj59Svhs0dhxyGqnHycuNGjukFQqjqxXXC2jqrPV2b09LuZEVedj1u+Ct0ZrKN+ZlmzUKZeewIks3X+NKFAP4wHIIeurzIIZJ4kbp1EWqIDJ+cYTPajOtBPCYqLbitLNEmX8J4HiAPm54xkb3OZvRaUMVF5Bf1ToVPgTjaD/w8bSScpoR54AcOkBbjfn3sgC0Owd2mBUZFreHDM1kzFNi7iI/dBwNweyONCJ1QFt+MVj8CQXyRwuiRVQsQikxN/GlkKvu5phJcozPor0Xw3Wgb42twiVqF4j+G/ta/w8g5gPriiMlrJxbNzpLJcPGEjgDf9zGLolBTOl63F+FllP/MgpD3vxiLhEcYqaF/2eV4qtpE=
